// Prisma client singleton.
// The real PrismaClient is generated by `npx prisma generate` — run that
// locally after setting DATABASE_URL in .env. Until then, the build
// uses a typed stub so type-checking passes without the generated client.


type AnyPrismaClient = any;

let prismaInstance: AnyPrismaClient;

function getPrismaClient(): AnyPrismaClient {
  if (prismaInstance) return prismaInstance;

  // No connection string configured at all — skip straight to offline
  // mode rather than waiting on a connection attempt that will time out.
  if (!process.env.DATABASE_URL) {
    return null;
  }

  try {
    // Will succeed once `npx prisma generate` has been run locally.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { PrismaClient } = require("@prisma/client");
    const globalForPrisma = globalThis as { prisma?: AnyPrismaClient };
    prismaInstance =
      globalForPrisma.prisma ??
      new PrismaClient({
        log:
          process.env.NODE_ENV === "development"
            ? ["warn", "error"]
            : ["error"],
      });
    if (process.env.NODE_ENV !== "production") {
      globalForPrisma.prisma = prismaInstance;
    }
    return prismaInstance;
  } catch {
    console.warn(
      "[prisma] @prisma/client not generated yet. " +
      "Run `npx prisma generate` after setting DATABASE_URL."
    );
    return null;
  }
}

export const prisma: AnyPrismaClient = getPrismaClient();
