"use client";

import { useEffect, useState } from "react";
import { Loader2, ShieldCheck } from "lucide-react";
import { Panel } from "@/components/ui/panel";

const labels: Record<string, string> = { REPORTS: "Reports", RECEIVE_SHIPMENTS: "Receive Shipments", MANAGE_BACKSTOCK: "Manage Back Stock", MANAGE_DISPLAY: "Manage Displays", MANAGE_GAMES: "Manage Games" };
const roleLabels: Record<string, string> = { OWNER: "Owner", MANAGER: "Manager", SHIFT_LEAD: "Shift Lead", EMPLOYEE: "Employee" };
interface DefaultPermission { role: string; permission: string; enabled: boolean }

export function RolePermissionPanel() {
  const [roles, setRoles] = useState<string[]>([]); const [permissions, setPermissions] = useState<string[]>([]); const [defaults, setDefaults] = useState<DefaultPermission[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { try { const response = await fetch("/api/platform/permissions", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load permissions."); setRoles(data.roles ?? []); setPermissions(data.permissions ?? []); setDefaults(data.defaults ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load permissions."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function toggle(role: string, permission: string, enabled: boolean) { const response = await fetch("/api/platform/permissions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role, permission, enabled }) }); if (response.ok) setDefaults((current) => [...current.filter((item) => !(item.role === role && item.permission === permission)), { role, permission, enabled }]); else setError((await response.json()).error || "Unable to update permission."); }
  return <Panel className="p-5"><div className="flex items-start gap-2"><ShieldCheck size={18} className="mt-0.5 text-accent" /><div><h3 className="text-base font-semibold text-text">Global Role &amp; Permission Defaults</h3><p className="mt-1 text-sm text-text-secondary">Set default capabilities for roles across customer deployments.</p></div></div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{loading ? <div className="mt-4 flex items-center gap-2 text-sm text-text-secondary"><Loader2 size={15} className="animate-spin" />Loading permissions...</div> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wide text-text-tertiary"><th className="py-2 pr-3">Role</th>{permissions.map((permission) => <th key={permission} className="py-2 pr-3">{labels[permission] ?? permission}</th>)}</tr></thead><tbody>{roles.map((role) => <tr key={role} className="border-b border-border last:border-0"><td className="py-3 pr-3 font-medium text-text">{roleLabels[role] ?? role}</td>{permissions.map((permission) => { const fixed = role === "OWNER" || role === "MANAGER"; const enabled = fixed || defaults.some((item) => item.role === role && item.permission === permission && item.enabled); return <td key={permission} className="py-3 pr-3"><label className="inline-flex items-center gap-2 text-xs text-text-secondary"><input type="checkbox" checked={enabled} disabled={fixed} onChange={(event) => { void toggle(role, permission, event.target.checked); }} />{fixed ? "Always" : enabled ? "Default" : "Off"}</label></td>; })}</tr>)}</tbody></table></div>}</Panel>;
}
