"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, CircleDollarSign, Minus, Plus, ReceiptText, ScanLine, Search, ShoppingCart, Ticket, X } from "lucide-react";

interface PosProps { employeeName: string; storeName: string; }
type Game = { id: string; number: string; name: string; price: number; available: number; color: string };
type CartLine = Game & { quantity: number };

const games: Game[] = [
  { id: "1234", number: "1234", name: "Cash 2", price: 5, available: 24, color: "bg-[#087da8]" },
  { id: "2456", number: "2456", name: "Lucky 5", price: 10, available: 18, color: "bg-[#159447]" },
  { id: "7812", number: "7812", name: "Gold Rush", price: 20, available: 12, color: "bg-[#e87512]" },
  { id: "9012", number: "9012", name: "Diamond 30", price: 30, available: 8, color: "bg-[#d41478]" },
  { id: "4321", number: "4321", name: "Mega Win", price: 15, available: 15, color: "bg-[#d92735]" },
  { id: "6789", number: "6789", name: "Silver Star", price: 2, available: 31, color: "bg-[#536b8d]" },
];

export function LotteryPos({ employeeName, storeName }: PosProps) {
  const [cart, setCart] = useState<CartLine[]>([]);
  const [selectedGame, setSelectedGame] = useState<Game | null>(null);
  const [quantity, setQuantity] = useState(1);
  const [searchOpen, setSearchOpen] = useState(false);
  const [scanOpen, setScanOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  const filteredGames = games.filter((game) => `${game.number} ${game.name} ${game.price}`.toLowerCase().includes(search.toLowerCase()));

  function openGame(game: Game) { setSelectedGame(game); setQuantity(1); setSearchOpen(false); }
  function addToSale() {
    if (!selectedGame) return;
    setCart((current) => { const existing = current.find((line) => line.id === selectedGame.id); return existing ? current.map((line) => line.id === selectedGame.id ? { ...line, quantity: Math.min(line.quantity + quantity, selectedGame.available) } : line) : [...current, { ...selectedGame, quantity }]; });
    setSelectedGame(null);
  }
  function adjust(id: string, amount: number) { setCart((current) => current.flatMap((line) => line.id === id ? (line.quantity + amount > 0 ? [{ ...line, quantity: Math.min(line.quantity + amount, line.available) }] : []) : [line])); }
  function resetSale() { setCart([]); setSelectedGame(null); setConfirmOpen(false); setSuccess(false); setError(false); }

  return <div className="min-h-full bg-[#f4f7fb] text-[#17233f]">
    <header className="border-b border-slate-200 bg-white px-5 py-3 sm:px-8"><div className="mx-auto flex max-w-[1366px] items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#087da8]">{storeName} · POS-01</p><h1 className="mt-1 text-2xl font-black tracking-tight">MAKE SALE</h1></div><div className="hidden items-center gap-6 text-right text-xs sm:flex"><div><p className="text-slate-500">Employee</p><p className="font-bold">{employeeName}</p></div><div><p className="text-slate-500">Terminal</p><p className="font-bold">POS-01</p></div><div><p className="text-slate-500">Current shift</p><p className="font-bold text-emerald-700">SHIFT 2 · OPEN</p></div></div><div className="text-right text-xs sm:hidden"><p className="font-bold">{employeeName}</p><p className="font-bold text-emerald-700">SHIFT 2 · OPEN</p></div></div></header>
    <main className="mx-auto grid max-w-[1366px] gap-5 px-5 py-5 sm:px-8 lg:grid-cols-[minmax(0,1fr)_370px] lg:py-6">
      <section><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-slate-500">Select a game to begin</p><h2 className="text-xl font-black sm:text-2xl">Available games</h2></div><div className="flex gap-2"><button type="button" onClick={() => setSearchOpen(true)} className="flex min-h-12 items-center gap-2 rounded-xl border-2 border-slate-200 bg-white px-4 font-bold hover:border-[#087da8]"><Search size={19} /> Search game</button><button type="button" onClick={() => setScanOpen(true)} className="flex min-h-12 items-center gap-2 rounded-xl bg-[#17233f] px-4 font-bold text-white hover:bg-[#24365d]"><ScanLine size={19} /> Scan</button></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4">{games.map((game) => <button key={game.id} type="button" onClick={() => openGame(game)} className={`flex min-h-[150px] flex-col justify-between rounded-xl p-4 text-left text-white shadow-[0_4px_0_rgba(23,35,63,0.14)] transition-transform hover:-translate-y-1 active:scale-[0.98] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#17233f] ${game.color}`}><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/20"><Ticket size={25} /></span><span className="rounded-full bg-black/15 px-2 py-1 text-[10px] font-black">GAME {game.number}</span></div><span><span className="block text-lg font-black sm:text-xl">{game.name}</span><span className="mt-1 block text-sm font-bold text-white/90">${game.price.toFixed(2)} · {game.available} available</span></span></button>)}</div><div className="mt-5 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-900"><CircleDollarSign size={18} /> Tap any card to choose quantity and add it to the sale.</div></section>
      <aside className="flex flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:min-h-[570px]"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div className="flex items-center gap-2"><ShoppingCart className="text-[#087da8]" size={22} /><h2 className="text-xl font-black">Current sale</h2></div>{cart.length > 0 && <button type="button" onClick={() => setCart([])} className="min-h-10 px-2 text-xs font-bold text-red-600 hover:underline">Clear</button>}</div><div className="min-h-[210px] flex-1 py-4">{cart.length === 0 ? <div className="flex h-full min-h-[200px] flex-col items-center justify-center text-center text-slate-400"><ReceiptText size={42} strokeWidth={1.5} /><p className="mt-3 font-bold">No tickets added</p><p className="mt-1 text-xs">Choose a game to build the sale.</p></div> : <div className="space-y-3">{cart.map((line) => <div key={line.id} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">Game {line.number}</p><p className="text-xs text-slate-500">{line.quantity} × ${line.price.toFixed(2)}</p></div><strong>${(line.quantity * line.price).toFixed(2)}</strong></div><div className="mt-2 flex items-center gap-2"><button type="button" onClick={() => adjust(line.id, -1)} className="min-h-10 min-w-10 rounded-lg border border-slate-200 bg-white p-2"><Minus size={16} className="mx-auto" /></button><span className="flex-1 text-center text-sm font-black">Quantity: {line.quantity}</span><button type="button" onClick={() => adjust(line.id, 1)} className="min-h-10 min-w-10 rounded-lg border border-slate-200 bg-white p-2"><Plus size={16} className="mx-auto" /></button></div></div>)}</div>}</div><div className="border-t border-slate-200 pt-4"><div className="flex items-center justify-between"><span className="font-semibold text-slate-500">TOTAL</span><span className="text-3xl font-black">${total.toFixed(2)}</span></div><button type="button" onClick={() => setConfirmOpen(true)} disabled={cart.length === 0} className="mt-4 min-h-14 w-full rounded-xl bg-[#087da8] text-lg font-black text-white hover:bg-[#066989] disabled:cursor-not-allowed disabled:bg-slate-300">MAKE SALE</button></div></aside>
    </main><div className="mx-auto flex max-w-[1366px] justify-between px-5 pb-5 text-xs font-semibold text-slate-500 sm:px-8"><Link href="/" className="inline-flex items-center gap-1 hover:text-[#087da8]"><ChevronLeft size={15} /> Back to home</Link><span>Mock POS interface · API integration later</span></div>

    {selectedGame && <Modal title={`GAME ${selectedGame.number}`} onClose={() => setSelectedGame(null)}><div className="grid grid-cols-2 gap-3"><Info label="Game" value={selectedGame.name} /><Info label="Price" value={`$${selectedGame.price.toFixed(2)}`} /><Info label="Available" value={`${selectedGame.available} packs`} /><Info label="Total" value={`$${(selectedGame.price * quantity).toFixed(2)}`} /></div><div className="mt-5"><p className="text-sm font-bold">Quantity</p><div className="mt-2 flex items-center justify-center gap-6"><button type="button" onClick={() => setQuantity((value) => Math.max(1, value - 1))} className="min-h-14 min-w-14 rounded-xl border-2 border-slate-200 bg-white text-2xl font-black"><Minus className="mx-auto" /></button><span className="w-16 text-center text-4xl font-black">{quantity}</span><button type="button" onClick={() => setQuantity((value) => Math.min(selectedGame.available, value + 1))} className="min-h-14 min-w-14 rounded-xl bg-[#087da8] text-2xl font-black text-white"><Plus className="mx-auto" /></button></div></div><div className="mt-6 flex gap-3"><button type="button" onClick={() => setSelectedGame(null)} className="min-h-14 flex-1 rounded-xl border-2 border-slate-200 font-bold">CANCEL</button><button type="button" onClick={addToSale} className="min-h-14 flex-[1.5] rounded-xl bg-[#087da8] font-black text-white">ADD TO SALE</button></div></Modal>}
    {searchOpen && <Modal title="SEARCH GAME" onClose={() => setSearchOpen(false)}><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Game number, name, or price" className="min-h-14 w-full rounded-xl border-2 border-slate-200 px-4 text-lg outline-none focus:border-[#087da8]" /><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{filteredGames.map((game) => <button key={game.id} type="button" onClick={() => openGame(game)} className="flex min-h-14 w-full items-center justify-between rounded-xl bg-slate-50 px-4 text-left hover:bg-blue-50"><span><strong>Game {game.number}</strong><span className="ml-2 text-sm text-slate-500">{game.name}</span></span><strong>${game.price.toFixed(2)}</strong></button>)}</div></Modal>}
    {scanOpen && <Modal title="SCAN" onClose={() => setScanOpen(false)}><div className="rounded-xl border-2 border-dashed border-[#087da8] bg-blue-50 p-8 text-center"><ScanLine className="mx-auto text-[#087da8]" size={55} /><p className="mt-4 text-lg font-black">Scanner ready</p><p className="mt-1 text-sm text-slate-600">This is a mock scanner for interface review.</p></div><button type="button" onClick={() => { setScanOpen(false); openGame(games[0]); }} className="mt-5 min-h-14 w-full rounded-xl bg-[#087da8] text-lg font-black text-white">MOCK SCAN GAME 1234</button></Modal>}
    {confirmOpen && <Modal title="CONFIRM SALE" onClose={() => setConfirmOpen(false)}><div className="space-y-2">{cart.map((line) => <div key={line.id} className="flex justify-between rounded-lg bg-slate-50 px-4 py-3 text-sm"><span>Game {line.number} · {line.quantity} × ${line.price}</span><strong>${(line.quantity * line.price).toFixed(2)}</strong></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-200 pt-4 text-xl font-black"><span>TOTAL</span><span>${total.toFixed(2)}</span></div><p className="mt-4 text-center text-sm text-slate-600">Are you sure you want to complete this sale?</p><div className="mt-5 flex gap-3"><button type="button" onClick={() => setConfirmOpen(false)} className="min-h-14 flex-1 rounded-xl border-2 border-slate-200 font-bold">CANCEL</button><button type="button" onClick={() => { setConfirmOpen(false); setSuccess(true); }} className="min-h-14 flex-[1.5] rounded-xl bg-[#087da8] font-black text-white">CONFIRM SALE</button></div><button type="button" onClick={() => { setConfirmOpen(false); setError(true); }} className="mt-3 w-full text-xs font-semibold text-slate-400 hover:text-red-600">Simulate error state</button></Modal>}
    {success && <Modal title="✓ SALE COMPLETE" onClose={resetSale}><div className="text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={60} /><p className="mt-4 text-sm font-bold uppercase tracking-wide text-slate-500">Total</p><p className="mt-1 text-4xl font-black">${total.toFixed(2)}</p><p className="mt-4 text-sm text-slate-500">Transaction</p><p className="font-mono text-lg font-black">#000184</p></div><button type="button" onClick={resetSale} className="mt-6 min-h-14 w-full rounded-xl bg-[#087da8] text-lg font-black text-white">NEW SALE</button></Modal>}
    {error && <Modal title="SALE COULD NOT BE COMPLETED" onClose={() => setError(false)}><div className="rounded-xl border border-red-200 bg-red-50 p-5 text-center text-red-800"><X className="mx-auto" size={35} /><p className="mt-3 font-bold">Unable to complete this transaction.</p></div><div className="mt-5 flex gap-3"><button type="button" onClick={() => setError(false)} className="min-h-14 flex-1 rounded-xl border-2 border-slate-200 font-bold">CANCEL</button><button type="button" onClick={() => { setError(false); setConfirmOpen(true); }} className="min-h-14 flex-1 rounded-xl bg-[#087da8] font-black text-white">TRY AGAIN</button></div></Modal>}
  </div>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#17233f]/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><h2 className="text-2xl font-black">{title}</h2><button type="button" aria-label="Close" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={21} /></button></div><div className="mt-5">{children}</div></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
