ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SHIFT_LEAD';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EMPLOYEE';
UPDATE users SET role = 'SHIFT_LEAD' WHERE role = 'CLERK';
UPDATE users SET role = 'EMPLOYEE' WHERE role = 'VIEWER';