"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Boxes, ChevronLeft, PackagePlus, Search, X } from "lucide-react";

export type InventoryPack = {
  id: string; game: string; gameNumber: string; serial: string; price: number; tickets: number; currentTicket: number;
  location: string; status: "BACK_STOCK" | "ACTIVE"; direction?: "FIRST" | "LAST"; invoice: string; receivedAt: string;
};
export type InventorySlot = { id: string; slotNumber: string; pack: InventoryPack | null };

export function InventoryPos({ employeeName, storeName, packs, slots }: { employeeName: string; storeName: string; packs: InventoryPack[]; slots: InventorySlot[] }) {
  const [view, setView] = useState<"BACK_STOCK" | "ACTIVE">("BACK_STOCK");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<InventoryPack | null>(null);
  const visible = useMemo(() => packs.filter((pack) => pack.status === view && `${pack.game} ${pack.gameNumber} ${pack.serial} ${pack.invoice} ${pack.location}`.toLowerCase().includes(search.toLowerCase())), [packs, search, view]);
  const activeCount = packs.filter((pack) => pack.status === "ACTIVE").length;
  const backCount = packs.filter((pack) => pack.status === "BACK_STOCK").length;
  const lowCount = packs.filter((pack) => pack.status === "ACTIVE" && pack.currentTicket > 0 && pack.currentTicket <= 5).length;

  return <div className="min-h-full bg-[#f4f7fb] text-[#17233f]">
    <header className="border-b border-slate-200 bg-white px-5 py-3 sm:px-8"><div className="mx-auto flex max-w-[1366px] items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#087da8]">{storeName} · Inventory control</p><h1 className="mt-1 text-2xl font-black tracking-tight">INVENTORY</h1></div><div className="hidden text-right text-xs sm:block"><p className="text-slate-500">Employee</p><p className="font-bold">{employeeName}</p></div></div></header>
    <main className="mx-auto max-w-[1366px] px-5 py-5 sm:px-8 sm:py-7">
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Summary label="Total packs" value={String(packs.length)} /><Summary label="Back stock" value={String(backCount)} tone="text-[#d41478]" /><Summary label="Active displays" value={String(activeCount)} tone="text-[#087da8]" /><Summary label="Low ticket alerts" value={String(lowCount)} tone="text-red-600" /></div>
      <div className="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-slate-500">Live store inventory</p><h2 className="mt-1 text-2xl font-black">Display map and pack list</h2></div><div className="flex flex-wrap gap-2"><Link href="/inventory/receive" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#159447] px-4 text-sm font-black text-white"><PackagePlus size={18} /> Receive stock</Link><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 text-slate-400" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search inventory" className="min-h-12 w-full rounded-xl border-2 border-slate-200 bg-white pl-10 pr-4 outline-none focus:border-[#087da8] sm:w-64" /></div></div></div>
      <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-black">Live store inventory</h3><p className="text-xs text-slate-500">Each display shows the tickets remaining in that position.</p></div><div className="flex flex-wrap gap-3 text-[11px] font-bold"><span className="inline-flex items-center gap-1.5"><i className="h-3 w-3 rounded-full bg-[#1688ff]" />Occupied</span><span className="inline-flex items-center gap-1.5"><i className="h-3 w-3 rounded-full bg-[#9ca3af]" />Empty</span></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{slots.length === 0 ? <div className="col-span-full rounded-xl border-2 border-dashed border-slate-300 p-8 text-center text-sm font-bold text-slate-500">No displays configured.</div> : slots.map((slot) => { const pack = slot.pack; const color = pack ? "border-[#1688ff] bg-[#1688ff] text-white hover:bg-[#0875e1]" : "border-[#9ca3af] bg-[#9ca3af] text-white hover:bg-[#858b96]"; return <button key={slot.id} type="button" onClick={() => pack && setSelected(pack)} disabled={!pack} className={`min-h-[104px] rounded-xl border-2 p-3 text-left shadow-sm transition ${color} ${!pack ? "cursor-default" : ""}`}><div className="flex items-start justify-between gap-2"><span className="text-xs font-black uppercase tracking-wide">Display {slot.slotNumber}</span><span className="h-2.5 w-2.5 rounded-full bg-white/80" /></div>{pack ? <p className="mt-7 text-3xl font-black">{pack.currentTicket}<span className="ml-1 text-xs font-bold uppercase">left</span></p> : <p className="mt-7 text-lg font-black uppercase">Empty</p>}</button>; })}</div></section>
      <div className="mt-5 flex gap-2 rounded-xl bg-slate-200 p-1"><button type="button" onClick={() => setView("BACK_STOCK")} className={`min-h-12 flex-1 rounded-lg text-sm font-black ${view === "BACK_STOCK" ? "bg-white text-[#17233f] shadow-sm" : "text-slate-500"}`}>BACK STOCK <span className="ml-1 rounded-full bg-pink-100 px-2 py-1 text-xs text-pink-700">{backCount}</span></button><button type="button" onClick={() => setView("ACTIVE")} className={`min-h-12 flex-1 rounded-lg text-sm font-black ${view === "ACTIVE" ? "bg-white text-[#17233f] shadow-sm" : "text-slate-500"}`}>ACTIVE STOCK <span className="ml-1 rounded-full bg-blue-100 px-2 py-1 text-xs text-blue-700">{activeCount}</span></button></div>
      <section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[1.2fr_1fr_1.4fr_0.9fr_0.8fr] gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3 text-[10px] font-black uppercase tracking-wide text-slate-500 sm:grid"><span>Game</span><span>Location</span><span>Serial</span><span>{view === "ACTIVE" ? "Current ticket" : "Tickets"}</span><span>Status</span></div>{visible.map((pack) => <button key={pack.id} type="button" onClick={() => setSelected(pack)} className="grid min-h-[76px] w-full grid-cols-[1fr_auto] items-center gap-3 border-b border-slate-100 px-4 py-3 text-left transition hover:bg-blue-50 focus-visible:bg-blue-50 focus-visible:outline-none sm:grid-cols-[1.2fr_1fr_1.4fr_0.9fr_0.8fr]"><div className="flex min-w-0 items-center gap-3"><span className={`hidden h-10 w-10 shrink-0 items-center justify-center rounded-lg sm:flex ${pack.status === "ACTIVE" ? "bg-blue-50 text-[#087da8]" : "bg-pink-50 text-[#d41478]"}`}><Boxes size={19} /></span><div className="min-w-0"><p className="truncate font-black">{pack.game} <span className="font-semibold text-slate-500">({pack.gameNumber})</span></p><p className="mt-1 text-xs text-slate-500">${pack.price.toFixed(2)} ticket</p></div></div><span className="text-sm font-bold">{pack.location}</span><span className="hidden truncate font-mono text-xs text-slate-500 sm:block">{pack.serial}</span><span className="hidden text-sm font-black sm:block">{pack.status === "ACTIVE" ? pack.currentTicket : pack.tickets}</span><span className={`justify-self-end rounded-full px-2 py-1 text-[10px] font-black sm:justify-self-start ${pack.status === "ACTIVE" ? "bg-blue-100 text-blue-700" : "bg-pink-100 text-pink-700"}`}>{pack.status === "ACTIVE" ? "ACTIVE" : "BACK"}</span></button>)}{visible.length === 0 && <div className="p-12 text-center text-slate-500"><Boxes className="mx-auto" size={38} /><p className="mt-3 font-bold">No inventory found</p><p className="mt-1 text-sm">Try another search or switch stock views.</p></div>}</section>
    </main><div className="mx-auto flex max-w-[1366px] justify-between px-5 pb-5 text-xs font-semibold text-slate-500 sm:px-8"><Link href="/" className="inline-flex items-center gap-1 hover:text-[#087da8]"><ChevronLeft size={15} /> Back to home</Link><span>{visible.length} rows shown · Tap any row for details</span></div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#17233f]/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#087da8]">Live pack details</p><h2 className="mt-1 text-2xl font-black">Game {selected.gameNumber}</h2></div><button type="button" onClick={() => setSelected(null)} aria-label="Close" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-5 grid grid-cols-2 gap-3"><Detail label="Game" value={selected.game} /><Detail label="Status" value={selected.status === "ACTIVE" ? "Active display" : "Back stock"} /><Detail label="Serial" value={selected.serial} /><Detail label="Location" value={selected.location} /><Detail label="Ticket price" value={`$${selected.price.toFixed(2)}`} /><Detail label={selected.status === "ACTIVE" ? "Current ticket" : "Tickets in pack"} value={String(selected.status === "ACTIVE" ? selected.currentTicket : selected.tickets)} />{selected.direction && <Detail label="Sell direction" value={`Sell from ${selected.direction === "FIRST" ? "First" : "Last"}`} />}<Detail label="Invoice" value={selected.invoice || "—"} /><Detail label="Received" value={new Date(selected.receivedAt).toLocaleDateString()} /></div><button type="button" onClick={() => setSelected(null)} className="mt-6 min-h-14 w-full rounded-xl bg-[#087da8] text-lg font-black text-white">Close details</button></div></div>}
  </div>;
}
function Summary({ label, value, tone = "text-[#17233f]" }: { label: string; value: string; tone?: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${tone}`}>{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-words font-bold">{value}</p></div>; }
