"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";

interface Exception { id: string; type: string; store: string; game: string; pack: string; display: string; expected: number | null; observed: number | null; timestamp: string | null; status: string }

export function CompanyExceptionsPanel() {
  const [exceptions, setExceptions] = useState<Exception[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const response = await fetch("/api/owner/exceptions", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load company exceptions."); setExceptions(data.exceptions ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load company exceptions."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  return <Panel className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-2"><AlertTriangle size={18} className="mt-0.5 text-red-600" /><div><p className="text-xs font-semibold uppercase tracking-wide text-text-tertiary">Company exception report</p><h2 className="text-base font-semibold text-text">Exceptions Across Stores</h2><p className="mt-1 text-sm text-text-secondary">Sequence locks and audit variances with store context.</p></div></div><Button size="sm" variant="outline" onClick={() => { void load(); }} disabled={loading}><RefreshCw size={13} className={loading ? "animate-spin" : ""} />Refresh</Button></div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{loading ? <div className="mt-4 flex items-center gap-2 text-sm text-text-secondary"><Loader2 size={15} className="animate-spin" />Loading company exceptions...</div> : exceptions.length === 0 ? <p className="mt-4 text-sm text-emerald-700">No company exceptions found.</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wide text-text-tertiary"><th className="py-2 pr-3">Store</th><th className="py-2 pr-3">Type</th><th className="py-2 pr-3">Pack / Game</th><th className="py-2 pr-3">Expected</th><th className="py-2 pr-3">Observed</th><th className="py-2">Status</th></tr></thead><tbody>{exceptions.map((item) => <tr key={`${item.type}-${item.id}`} className="border-b border-border last:border-0"><td className="py-2.5 pr-3 font-medium text-text">{item.store}</td><td className="py-2.5 pr-3 text-xs text-text-secondary">{item.type.replaceAll("_", " ")}</td><td className="py-2.5 pr-3"><span className="font-mono text-xs">{item.pack}</span><br /><span className="text-xs text-text-secondary">{item.game} · Display {item.display}</span></td><td className="py-2.5 pr-3">{item.expected ?? "-"}</td><td className="py-2.5 pr-3">{item.observed ?? "-"}</td><td className={`py-2.5 font-semibold ${item.status === "RESOLVED" ? "text-emerald-700" : "text-red-700"}`}>{item.status}</td></tr>)}</tbody></table></div>}</Panel>;
}
