"use client";

import { useEffect, useState } from "react";
import { Download, Loader2, Package, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";

interface Pack { store: string; gameNumber: string; game: string; serialNumber: string; status: string; display: string; receivedAt: string; currentTicket: number | null; quantity: number | null; price: number }
const statuses = ["", "RECEIVING", "BACK_STOCK", "ACTIVE", "SOLD_OUT", "RETURNED"];

export function CompanyInventoryPanel() {
  const [packs, setPacks] = useState<Pack[]>([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load(nextStatus = status) { setLoading(true); setError(""); try { const response = await fetch(`/api/owner/inventory${nextStatus ? `?status=${nextStatus}` : ""}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load company inventory."); setPacks(data.packs ?? []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load company inventory."); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [status]);
  return <Panel className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-2"><Package size={18} className="mt-0.5 text-accent" /><div><p className="text-xs font-semibold uppercase tracking-wide text-text-tertiary">Company inventory report</p><h2 className="text-base font-semibold text-text">Inventory Across Stores</h2><p className="mt-1 text-sm text-text-secondary">Pack lifecycle, display position, and ticket status across authorized locations.</p></div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { void load(); }} disabled={loading}><RefreshCw size={13} className={loading ? "animate-spin" : ""} />Refresh</Button><Button size="sm" variant="secondary" onClick={() => window.open(`/api/owner/inventory?${status ? `status=${status}&` : ""}format=csv`, "_blank")}><Download size={13} />Export CSV</Button></div></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-4 rounded-md border border-border bg-surface px-3 py-2 text-sm"><option value="">All statuses</option>{statuses.slice(1).map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{loading ? <div className="mt-4 flex items-center gap-2 text-sm text-text-secondary"><Loader2 size={15} className="animate-spin" />Loading inventory...</div> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wide text-text-tertiary"><th className="py-2 pr-3">Store</th><th className="py-2 pr-3">Game / Pack</th><th className="py-2 pr-3">Status</th><th className="py-2 pr-3">Display</th><th className="py-2 pr-3">Current</th><th className="py-2">Received</th></tr></thead><tbody>{packs.map((pack) => <tr key={`${pack.store}-${pack.serialNumber}`} className="border-b border-border last:border-0"><td className="py-2.5 pr-3 font-medium text-text">{pack.store}</td><td className="py-2.5 pr-3"><span className="font-mono text-xs">{pack.serialNumber}</span><br /><span className="text-xs text-text-secondary">#{pack.gameNumber} {pack.game}</span></td><td className="py-2.5 pr-3 text-xs text-text-secondary">{pack.status.replaceAll("_", " ")}</td><td className="py-2.5 pr-3 text-text-secondary">{pack.display || "-"}</td><td className="py-2.5 pr-3 text-text-secondary">{pack.currentTicket ?? "-"}</td><td className="py-2.5 text-xs text-text-tertiary">{new Date(pack.receivedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</Panel>;
}
